### ISSUE TITLE
[Issues]Aways soft ban

### ISSUE THREAD

**Issue by HineekoRM** [gosimulate/gosimulator#2] opened 2016-08-12 13:07 UTC
Hi i'm use GoBot but i have problem
1.my main user "aways" detect soft ban and can't catch Pokemon but it can loot PokeStop
2.i try to login other account but it can work very well
3.When i login to Pokemon Go i can catch Pokemon normally not have a problem it have only GoBotSim
4.Long time (may be permanant) to detect probable soft ban and fix it
5.I have try to use other device to log in my Main ID but it have same problem i think it have problem about app server aways fail to catch Pokemons

*Photo
1.This is my main ID
 http://imgur.com/dV4JC3N
2.This is my other ID 
http://imgur.com/fDmZiNG
same device same app but ? why ?

Thanks. i'll back to see this

**Comment by dees040** [comment] 2016-08-12 13:09
Does the app detect the soft ban?

**Comment by HineekoRM** [comment] 2016-08-12 13:11
Yes aways detect soft ban after remove it it can loot PokeStop but can't catch pokemon and detect soft ban again

**Comment by HineekoRM** [comment] 2016-08-12 13:21
update picture

**Comment by dees040** [comment] 2016-08-12 13:23
Time to make your 'Other ID' the 'Main ID' I guess :grin:.

**Comment by nonamedeadpool** [comment] 2016-08-12 13:24
yes this is happening to mine to how can I fix this

**Comment by HineekoRM** [comment] 2016-08-12 13:25
Hmmm i'm seriously to use this my main ID now i try to use other device wait for a result

**Comment by HineekoRM** [comment] 2016-08-12 13:47
update to use other device = =

**Comment by nonamedeadpool** [comment] 2016-08-12 13:50
did it work ?

**Comment by HineekoRM** [comment] 2016-08-12 13:50
no doesn't work anymore

**Comment by nonamedeadpool** [comment] 2016-08-12 13:51
this is happening to me. I hope this gets fixed or whatever is happening.

**Comment by nonamedeadpool** [comment] 2016-08-12 13:55
I doubt this is Niantics doing. more people would post here. And we would of been permabanned. so something else is wrong.

**Comment by HineekoRM** [comment] 2016-08-12 14:05
i loged in my account but no problem it can catch pokemon normally

**Comment by nonamedeadpool** [comment] 2016-08-12 14:14
I can't catch any pokemon on my pokemon go app  but I can Loot stops and battle gyms

**Comment by HineekoRM** [comment] 2016-08-12 14:15
oh shit wtf same me now i would like to have your fb your mind ?deadpool

**Comment by nonamedeadpool** [comment] 2016-08-12 14:18
I don't have Facebook. I barley made this account to post here. I can only battle gyms and Loot stops . unable to catch pokemon. maybe Niantic did this?

**Comment by HineekoRM** [comment] 2016-08-12 14:22
i think wait tomorrow and i will check it again

**Comment by nonamedeadpool** [comment] 2016-08-12 14:23
same here

**Comment by nonamedeadpool** [comment] 2016-08-12 14:26
if Niantic did this, they would of did this to all my accounts at once, so I don't know what's happening. I use multiple accounts and bot them all, but this only happens to one account. so this stumps me.

**Comment by HineekoRM** [comment] 2016-08-12 14:32
same me it have only my 1 account of 10 = =" but my main hehe go to building new account

**Comment by nonamedeadpool** [comment] 2016-08-12 14:42
I googled and another bot forum and they say it's Niantic server issues and that someone had multiple people happen to them and multiple had not . so I'm guessing Niantic fucked up trying to do something. so don't get worries

**Comment by HineekoRM** [comment] 2016-08-12 14:44
what's wrong thay punish who have multiple account ?

**Comment by scissors14** [comment] 2016-08-12 16:32
I can only loot pokestops. When i catch pokemon manually and through the simulator the pokemon run away. This started happening around 3am central time on all my accounts 

The issue i believe has something to do with changing paths to often.
My account i just made can bot and catch pokemon with ease  so i think its a lock on my main account.

**Comment by nonamedeadpool** [comment] 2016-08-12 17:13
yea it happened around 3 am. but I read on another bot forums that to this one guy it happened to his older brother and him but not to his younger brother. but only he botted.

**Comment by nonamedeadpool** [comment] 2016-08-12 17:14
if anything there should be more people posting here if that happened to bulk people ? I had my speed on medium so I doubt it was patterns of how they change to pokestops. so idk

**Comment by nonamedeadpool** [comment] 2016-08-12 17:21
this is what I found 
https://www.thebuddyforum.com/pokefarmer-forum/254100-official-current-situation-looting-fleeing-idle.html?s=78c8bbc65369d5fd91a7899d642da3c8

it says it's a soft ban. not 100% though.

**Comment by VernMcC** [comment] 2016-08-12 20:51
I think it hit my test account too. Go to tries to remove the ban,  but since the pokestops gives loot, the ban removal does not appear to work right.  I cannot do it manually either by spoofing GPS and working a stop.

**Comment by nonamedeadpool** [comment] 2016-08-12 21:05
rumor is its a shadowban. it's only a rumor.

**Comment by FriendZoneKing** [comment] 2016-08-12 22:26
Still has the softban, simulator can unban and catch pokemons flawlessly, but when catching on the actual game it still won't let me catch one, always breaking free.  I tried to create a fresh account just to test, if i will still get banned even if i dont cross continents by not putting a pre destined route, at the application it catches, but when i go back at the actual game, its already banned... hope you can take a look and test in the actual game. thanks

**Comment by nonamedeadpool** [comment] 2016-08-12 22:31
it has been confirmed by a few people if you wait a set amount of time you can catch pokemon again.  hopefully this is true. one person said . he caught his last pokemon 7:50am wasn't able to catch anymore till 7:50pm.

**Comment by VernMcC** [comment] 2016-08-12 22:34
2 hrs and I can catch with the account again.  No clue what set the ban.  I was running NY South with no big location moves on test account.

**Comment by nonamedeadpool** [comment] 2016-08-12 22:34
there saying that maybe that the speed at which we go makes the pop up if your the passenger page on your pokemon go app and if you don't click it it triggers a 12-24 hour soft ban.

**Comment by FriendZoneKing** [comment] 2016-08-12 22:37
oh.. can i be offline while waiting for the ban to be removed? or i have to open the app while waiting?

**Comment by nonamedeadpool** [comment] 2016-08-12 22:46
awesome I'm not banned anymore. I got banned at 2:40am and I just started up my pokemon go app and turned gps on and tried to catch a pokemon at 3:46 pm and it worked. I can catch pokemon now. it's a 12 hour soft ban

**Comment by VernMcC** [comment] 2016-08-12 22:46
I spoke too soon.  I caught a couple on the start of the NY South rout and then the same thin.  I could loot stops,  I could not catch critters. I forced a soft ban by moving to another city,  and the bot removed the ban,  but still will not get critters.  I had the speed on medium.  I will wait at least two hours and try again on slow.

**Comment by nonamedeadpool** [comment] 2016-08-12 22:47
now we just have to wait to see what causes the ban so we can bypass  this soft ban..  I wouldn't recommend logging in your pokemon go app and botting at the same time. even with gps off

**Comment by nonamedeadpool** [comment] 2016-08-12 22:48
vern. your soft banned for 12 hours now. you should of tried with gps on and tried it yourself. we don't know what triggers the ban yet. I just got off my 12 hour ban and I can catch pokemon

**Comment by VernMcC** [comment] 2016-08-12 22:56
Nonamedeadpool, I did spoof GPS to the spot and collected a couple after 2 hours off line.  Force killed pogo app and started bot.  I was in same spot in spoofed GPS session as start of NY South route.  Bot collected a couple critters,  then started failing again.  I have plenty of  room and enough poke balls to collect.  Failed on a 10cp rat,  so it was not some series of high value failures.. I then jumpedabout three hundred miles.  Observed the traditional soft ban affect, nothing from stops and and no critters.  The bot reported soft ban detected and removed it.  The bot could then collect from stops but critters still fled.

**Comment by scissors14** [comment] 2016-08-12 23:01
After 13 hours of being softbanned (pokestops worked and catching pokemon didn't ) i have finally been unfroze.

Catching pokemon fine after 13 hours of being unable to catch pokemon.

**Comment by HineekoRM** [comment] 2016-08-13 01:31
12 Hr later i know what must i do change the speed to low for account has soft ban now i bot normally

**Comment by gr33nd3v1l** [comment] 2016-08-13 11:55
This is a different kind of ban. Lets call it a freeze, it takes anywhere from 12 to 24 hours to clear.

Remember dont jump continents obviously. Use your brain

**Comment by VernMcC** [comment] 2016-08-13 17:16
Intersting observation. After 12 hours it worked in NY South route on slow.  After about an hour it appeared to have this new freeze back in place,  I could loot stops but all critters ran away. So I stopped bot and switched to Boston Route and it was working fine after lifting the fast move soft ban.

**Comment by afarinah1234** [comment] 2016-08-14 04:44
Use vpn to hide ip when you jump far from location and wait 30mnt to 1 hour. Otherwise niatic will notice your IP and get soft ban.

**Comment by clivejo** [comment] 2016-08-14 12:36
I want be sure i've understand... I've got tihs ban tonight when bot in ny south route. Sometimes i access from ios pogo app with gps disabled just for manage bag. I'm in Italy. i've stop bot about 6hrs ago, in the meanwhile i've acces from italy without vpn. So what is the best way now to get away the ban?

**Comment by HineekoRM** [comment] 2016-08-14 13:46
no way to safe your account now, i think o.O im just bot in NY with login and logout  a shot time to safe my account

**Comment by gr33nd3v1l** [comment] 2016-08-14 14:07
Thread has been discussed.

**Closed by gr33nd3v1l** 2016-08-14 14:07 UTC
